"""The vocabulary the rest of the package is written in."""

from __future__ import annotations

from pathlib import Path
from typing import Any
import re

VERSION = "0.3.0"  # x-release-please-version

# The shapes this module passes around. All JSON-shaped: the report is written
# out as JSON and read back by the extension, so nothing here is richer than
# what survives that round trip.
Stats = dict[str, Any]
Report = dict[str, Any]
Finding = dict[str, Any]
FileInfo = dict[str, Any]
Profile = dict[str, Any]
MAX_FILE_BYTES = 512 * 1024

# The defaults the analysis runs with. Named because each is a judgement about
# what is worth reporting, not an arbitrary number: a signature longer than
# SIGNATURE_SPAN is not a signature, eight identical lines is a copy rather
# than a coincidence, and a list of twenty is as much as anyone acts on.
SIGNATURE_SPAN = 400
DUPE_WINDOW = 8
DUPE_LIMIT = 20
CYCLE_LIMIT = 10
HOTSPOT_LIMIT = 10
TOP_RECOMMENDATIONS = 5
BAR_WIDTH = 20

# The thresholds the rubric judges by. Each is a claim about what counts as bad
# enough to report, so each gets a name instead of appearing as a number in the
# middle of a condition.
MINIFIED_LINE_CHARS = 500  # one line this long is a bundle, not code
SIGNATURE_SCAN_CHARS = 400  # past this, the "(" found is not this signature
MIN_FILES_FOR_HOTSPOTS = 5  # fewer, and the average means nothing
MIN_CHANGED_FOR_HOTSPOTS = 3
MAX_CONCERNS_PER_FILE = 3  # a fourth concern is a module doing four jobs
MIN_NAME_CHARS = 2  # `i`, `x`, `db` — anything shorter says nothing
GOD_FILE_LINES = 400
GOD_FILE_FUNCTIONS = 20
WIDE_INTERFACE_METHODS = 7  # an interface this wide has more than one client
GOD_CLASS_METHODS = 15
REPEATED_LITERAL_USES = 4  # the fourth copy is a constant waiting to happen
DEAD_NAME_CHARS = 3  # shorter names collide with words in prose
MAX_DEAD_CODE_FINDINGS = 20
MIN_FUNCTIONS_FOR_COHESION = 3
MIN_MODULES_FOR_COUPLING = 3
MIN_POINTS_LOST_TO_RECOMMEND = 0.5
HIGH_SEVERITY_RANK = 2
MEDIUM_SEVERITY_RANK = 6

# 10/100/1000 and 24/60 are units, not magic numbers: they read as themselves
# wherever they appear.
UNIT_LITERALS = {"10", "100", "1000", "24", "60"}

SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "bower_components",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".tox",
    ".nox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".gradle",
    ".idea",
    ".vscode",
    ".next",
    ".nuxt",
    ".terraform",
    "vendor",
    "third_party",
    "site-packages",
    ".cache",
    ".yarn",
    "Pods",
    "migrations",
}
ARTIFACT_DIRS = {
    "coverage",
    "htmlcov",
    "build",
    "dist",
    "target",
    "out",
    "obj",
    "reports",
    ".nyc_output",
    "generated",
    "gen",
    "proto",
    "pb",
    "swagger",
    "openapi",
}

# Generated and minified files are not written by anyone and score terribly on
# every principle; scoring them says nothing about the code someone maintains.
GENERATED_RE = re.compile(
    r"@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated"
    r"|generated by protoc|generated by the protocol buffer|@dart=|machine generated",
    re.IGNORECASE,
)
GENERATED_NAME_RE = re.compile(
    r"\.min\.\w+$|\.pb\.\w+$|_pb2(?:_grpc)?\.py$|\.g\.\w+$"
    r"|\.generated\.\w+$|_generated\.\w+$"
)


def is_generated(rel: Path, text: str) -> bool:
    if GENERATED_NAME_RE.search(rel.name):
        return True
    if GENERATED_RE.search(text[:2000]):
        return True
    # A minified bundle: one enormous line rather than code anyone reads.
    return any(len(line) > MINIFIED_LINE_CHARS for line in text.splitlines()[:50])


LANG_BY_EXT = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".go": "go",
    ".java": "java",
    ".kt": "kotlin",
    ".rb": "ruby",
    ".php": "php",
    ".rs": "rust",
    ".cs": "csharp",
    ".ex": "elixir",
    ".exs": "elixir",
    ".scala": "scala",
    ".swift": "swift",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".lua": "lua",
    ".sh": "shell",
    ".bash": "shell",
}
JS_EXT = {".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx"}
BRACE_LANGS = {
    "javascript",
    "typescript",
    "go",
    "java",
    "kotlin",
    "php",
    "rust",
    "csharp",
    "scala",
    "swift",
    "c",
    "cpp",
}
TEST_DIR_NAMES = {"test", "tests", "spec", "specs", "__tests__", "testing", "e2e", "features"}

