#!/usr/bin/env python3
"""gradebook-code — score a codebase against DRY, YAGNI, GRASP, SOLID and KISS.

The principles are famous and the arguments about them are endless, so this
scores the *observable* consequences: how complex the functions are, how much
is copy-pasted, how wide the classes are, how far the dependencies reach, how
much abstraction exists for a single caller. Every finding carries a file and
a line, because "SRP 4.1/10" is not something anyone can act on.

  gradebook-code .
  gradebook-code /path/to/repo --format markdown
  gradebook-code . --fail-under 60 --by-dir
"""

import argparse
import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

VERSION = "0.1.0"  # x-release-please-version
MAX_FILE_BYTES = 512 * 1024

SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "bower_components",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".tox",
    ".nox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".gradle",
    ".idea",
    ".vscode",
    ".next",
    ".nuxt",
    ".terraform",
    "vendor",
    "third_party",
    "site-packages",
    ".cache",
    ".yarn",
    "Pods",
    "migrations",
}
ARTIFACT_DIRS = {
    "coverage",
    "htmlcov",
    "build",
    "dist",
    "target",
    "out",
    "obj",
    "reports",
    ".nyc_output",
    "generated",
    "gen",
    "proto",
    "pb",
    "swagger",
    "openapi",
}

# Generated and minified files are not written by anyone and score terribly on
# every principle; scoring them says nothing about the code someone maintains.
GENERATED_RE = re.compile(
    r"@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated"
    r"|generated by protoc|generated by the protocol buffer|@dart=|machine generated",
    re.IGNORECASE,
)
GENERATED_NAME_RE = re.compile(
    r"\.min\.\w+$|\.pb\.\w+$|_pb2(?:_grpc)?\.py$|\.g\.\w+$"
    r"|\.generated\.\w+$|_generated\.\w+$"
)


def is_generated(rel: Path, text: str):
    if GENERATED_NAME_RE.search(rel.name):
        return True
    if GENERATED_RE.search(text[:2000]):
        return True
    # A minified bundle: one enormous line rather than code anyone reads.
    return any(len(line) > 500 for line in text.splitlines()[:50])


LANG_BY_EXT = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".go": "go",
    ".java": "java",
    ".kt": "kotlin",
    ".rb": "ruby",
    ".php": "php",
    ".rs": "rust",
    ".cs": "csharp",
    ".ex": "elixir",
    ".exs": "elixir",
    ".scala": "scala",
    ".swift": "swift",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".lua": "lua",
    ".sh": "shell",
    ".bash": "shell",
}
JS_EXT = {".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx"}
BRACE_LANGS = {
    "javascript",
    "typescript",
    "go",
    "java",
    "kotlin",
    "php",
    "rust",
    "csharp",
    "scala",
    "swift",
    "c",
    "cpp",
}
TEST_DIR_NAMES = {"test", "tests", "spec", "specs", "__tests__", "testing", "e2e", "features"}

# ------------------------------------------------------------- declarations

FUNC_RE = {
    "python": re.compile(r"^([ \t]*)(?:async[ \t]+)?def[ \t]+(\w+)[ \t]*\(", re.MULTILINE),
    "javascript": re.compile(
        r"^([ \t]*)(?:export[ \t]+)?(?:async[ \t]+)?function[ \t]+(\w+)[ \t]*\("
        r"|^([ \t]*)(?:export[ \t]+)?(?:const|let)[ \t]+(\w+)[ \t]*=[ \t]*(?:async[ \t]+)?\("
        r"|^([ \t]*)(?:public|private|protected|static|async)*[ \t]*(\w+)[ \t]*\([^)]*\)[ \t]*\{",
        re.MULTILINE,
    ),
    "go": re.compile(r"^()func[ \t]+(?:\([^)]*\)[ \t]*)?(\w+)[ \t]*\(", re.MULTILINE),
    "java": re.compile(
        r"^([ \t]*)(?:@\w+[ \t]*)*(?:public|private|protected|static|final|synchronized"
        r"|abstract|native)[\w<>\[\], \t]*[ \t](\w+)[ \t]*\([^;]*\)[ \t]*\{",
        re.MULTILINE,
    ),
    "ruby": re.compile(r"^([ \t]*)def[ \t]+(\w+[?!]?)", re.MULTILINE),
    "php": re.compile(
        r"^([ \t]*)(?:(?:public|private|protected|static|final|abstract)[ \t]+)*"
        r"function[ \t]+(\w+)[ \t]*\(",
        re.MULTILINE,
    ),
    "rust": re.compile(
        r"^([ \t]*)(?:pub(?:\([^)]*\))?[ \t]+)?(?:async[ \t]+)?fn[ \t]+(\w+)", re.MULTILINE
    ),
    "csharp": re.compile(
        r"^([ \t]*)(?:\[[^\]]*\][ \t]*)*(?:public|private|protected|internal"
        r"|static|async|override|virtual)[\w<>\[\], \t]*[ \t](\w+)[ \t]*\("
        r"[^;]*\)[ \t]*\{",
        re.MULTILINE,
    ),
    "elixir": re.compile(r"^([ \t]*)defp?[ \t]+(\w+[?!]?)", re.MULTILINE),
    "scala": re.compile(
        r"^([ \t]*)(?:override[ \t]+)?(?:private[ \t]+)?def[ \t]+(\w+)", re.MULTILINE
    ),
    "shell": re.compile(r"^()(?:function[ \t]+)?(\w+)[ \t]*\(\)[ \t]*\{", re.MULTILINE),
    "lua": re.compile(r"^([ \t]*)(?:local[ \t]+)?function[ \t]+([\w.:]+)", re.MULTILINE),
}
FUNC_RE["typescript"] = FUNC_RE["javascript"]
FUNC_RE["kotlin"] = re.compile(
    r"^([ \t]*)(?:(?:private|internal|public|override|suspend)[ \t]+)*"
    r"fun[ \t]+(?:<[^>]+>[ \t]*)?(\w+)[ \t]*\(",
    re.MULTILINE,
)
for _lang in ("c", "cpp", "swift"):
    FUNC_RE.setdefault(
        _lang, re.compile(r"^()[\w:<>*&\[\] \t]+?(\w+)[ \t]*\([^;]*\)[ \t]*\{", re.MULTILINE)
    )

CLASS_RE = {
    "python": re.compile(r"^[ \t]*class[ \t]+(\w+)[ \t]*(?:\(([^)]*)\))?", re.MULTILINE),
    "javascript": re.compile(
        r"^[ \t]*(?:export[ \t]+)?(?:default[ \t]+)?class[ \t]+(\w+)"
        r"(?:[ \t]+extends[ \t]+([\w.]+))?",
        re.MULTILINE,
    ),
    "java": re.compile(
        r"^[ \t]*(?:public|private|protected|final|abstract|static|[ \t])*"
        r"(?:class|interface|enum|record)[ \t]+(\w+)"
        r"((?:[ \t]+(?:extends|implements)[ \t]+[\w., <>]+)?)",
        re.MULTILINE,
    ),
    "go": re.compile(r"^type[ \t]+(\w+)[ \t]+(struct|interface)", re.MULTILINE),
    "ruby": re.compile(
        r"^[ \t]*(?:class|module)[ \t]+(\w+)(?:[ \t]*<[ \t]*([\w:]+))?", re.MULTILINE
    ),
    "php": re.compile(
        r"^[ \t]*(?:final[ \t]+|abstract[ \t]+)?(?:class|interface|trait)[ \t]+(\w+)"
        r"((?:[ \t]+(?:extends|implements)[ \t]+[\w, \\]+)?)",
        re.MULTILINE,
    ),
    "rust": re.compile(r"^[ \t]*(?:pub[ \t]+)?(?:struct|enum|trait)[ \t]+(\w+)()", re.MULTILINE),
    "csharp": re.compile(
        r"^[ \t]*(?:public|private|protected|internal|sealed|abstract|static"
        r"|partial|[ \t])*(?:class|interface|record|struct)[ \t]+(\w+)"
        r"([ \t]*:[ \t]*[\w, <>]+)?",
        re.MULTILINE,
    ),
    "elixir": re.compile(r"^[ \t]*defmodule[ \t]+([\w.]+)()", re.MULTILINE),
    "scala": re.compile(
        r"^[ \t]*(?:case[ \t]+)?(?:class|object|trait)[ \t]+(\w+)"
        r"((?:[ \t]+extends[ \t]+[\w, \[\]]+)?)",
        re.MULTILINE,
    ),
}
CLASS_RE["typescript"] = re.compile(
    r"^[ \t]*(?:export[ \t]+)?(?:default[ \t]+)?(?:abstract[ \t]+)?(?:class|interface)[ \t]+(\w+)"
    r"((?:[ \t]+(?:extends|implements)[ \t]+[\w., <>]+)?)",
    re.MULTILINE,
)
CLASS_RE["kotlin"] = re.compile(
    r"^[ \t]*(?:(?:open|abstract|sealed|data|internal|private)[ \t]+)*"
    r"(?:class|interface|object)[ \t]+(\w+)([^\n{]*)",
    re.MULTILINE,
)

IMPORT_RE = {
    # `from pkg import module` names the dependency in the second group, so both
    # halves are kept and resolved against the repo's own module names.
    "python": re.compile(
        r"^[ \t]*(?:from[ \t]+([.\w]+)[ \t]+import[ \t]+([^\n#]+)"
        r"|import[ \t]+([.\w]+))",
        re.MULTILINE,
    ),
    "javascript": re.compile(
        r"""^[ \t]*import[^'"\n]*['"]([^'"]+)['"]"""
        r"""|require\(\s*['"]([^'"]+)['"]\s*\)""",
        re.MULTILINE,
    ),
    "go": re.compile(r'^[ \t]*(?:_[ \t]+|\w+[ \t]+)?"([^"]+)"', re.MULTILINE),
    "java": re.compile(r"^[ \t]*import[ \t]+(?:static[ \t]+)?([\w.]+)", re.MULTILINE),
    "ruby": re.compile(r"^[ \t]*require(?:_relative)?[ \t]+['\"]([^'\"]+)['\"]", re.MULTILINE),
    "php": re.compile(r"^[ \t]*use[ \t]+([\w\\]+)", re.MULTILINE),
    "rust": re.compile(r"^[ \t]*(?:pub[ \t]+)?use[ \t]+([\w:]+)", re.MULTILINE),
    "csharp": re.compile(r"^[ \t]*using[ \t]+(?:static[ \t]+)?([\w.]+)", re.MULTILINE),
    "elixir": re.compile(r"^[ \t]*(?:alias|import|use)[ \t]+([\w.]+)", re.MULTILINE),
    "scala": re.compile(r"^[ \t]*import[ \t]+([\w.]+)", re.MULTILINE),
}
IMPORT_RE["typescript"] = IMPORT_RE["javascript"]
IMPORT_RE["kotlin"] = IMPORT_RE["java"]

# --------------------------------------------------------------- scanning

# Every metric below counts keywords, braces and dots. Counting the ones that
# live inside comments and string literals is the single largest source of
# error in a regex-based reader: a docstring that says "if the kind is a
# circle, for squares, while you are at it" adds four branches to a function
# that has none. Blanking them first is what makes the numbers mean anything —
# and it works the same way for every language rather than only where a parser
# happens to be available.
LINE_COMMENTS = {
    "python": ("#",),
    "ruby": ("#",),
    "shell": ("#",),
    "elixir": ("#",),
    "lua": ("--",),
    "php": ("//", "#"),
    "sql": ("--",),
}
BLOCK_COMMENTS = {
    "lua": (("--[[", "]]"),),
    "ruby": (("=begin", "=end"),),
    "python": (),
    "shell": (),
    "elixir": (),
}
STRING_QUOTES = {
    "go": ('"', "'", "`"),
    "javascript": ('"', "'", "`"),
    "typescript": ('"', "'", "`"),
    "scala": ('"',),
    "elixir": ('"', "'"),
    "shell": ('"', "'"),
}
TRIPLE_QUOTE_LANGS = {"python", "scala", "elixir", "kotlin"}
DEFAULT_LINE_COMMENTS = ("//",)
DEFAULT_BLOCK_COMMENTS = (("/*", "*/"),)
DEFAULT_QUOTES = ('"', "'")


def strip_noise(text: str, lang: str):
    """Blank comments and string contents, preserving length and line numbers.

    Offsets are unchanged, so every line number reported against the result is
    still correct against the original file.
    """
    line_tokens = LINE_COMMENTS.get(lang, DEFAULT_LINE_COMMENTS)
    block_pairs = BLOCK_COMMENTS.get(lang, DEFAULT_BLOCK_COMMENTS)
    quotes = STRING_QUOTES.get(lang, DEFAULT_QUOTES)
    triple = lang in TRIPLE_QUOTE_LANGS
    out = list(text)
    size = len(text)

    def blank(start, end):
        for index in range(max(start, 0), min(end, size)):
            if out[index] != "\n":
                out[index] = " "

    position = 0
    while position < size:
        char = text[position]
        token = next((t for t in line_tokens if text.startswith(t, position)), None)
        if token:
            end = text.find("\n", position)
            end = size if end == -1 else end
            blank(position, end)
            position = end
            continue
        pair = next((p for p in block_pairs if text.startswith(p[0], position)), None)
        if pair:
            end = text.find(pair[1], position + len(pair[0]))
            end = size if end == -1 else end + len(pair[1])
            blank(position, end)
            position = end
            continue
        if char in quotes:
            if triple and text.startswith(char * 3, position):
                end = text.find(char * 3, position + 3)
                end = size if end == -1 else end + 3
                blank(position + 3, end - 3)
                position = end
                continue
            cursor = position + 1
            while cursor < size:
                if text[cursor] == "\\":
                    cursor += 2
                    continue
                if text[cursor] == char or text[cursor] == "\n":
                    break
                cursor += 1
            blank(position + 1, cursor)
            position = min(cursor + 1, size)
            continue
        position += 1
    return "".join(out)


# ------------------------------------------------------------------ metrics

DECISION_RE = re.compile(
    r"(?<![.\w])(?:if|elif|else\s+if|elsif|for|foreach|while|case|when|catch|rescue|except)"
    r"(?![\w])|&&|\|\||\?(?=[^:\n]{1,60}:)|(?<![.\w])and(?![\w])|(?<![.\w])or(?![\w])"
)
DEMETER_RE = re.compile(r"(?<![\w.])(?!self\.|this\.|super\.)\w+(?:\.\w+){3,}")
MAGIC_NUMBER_RE = re.compile(r"(?<![\w.])\d{2,}(?:\.\d+)?(?![\w.])")
COMMENTED_CODE_RE = re.compile(
    r"^[ \t]*(?://|#)[ \t]*(?:if|for|while|return|def |func |function |class |import |from |var "
    r"|let |const |print|console\.|[\w.]+\s*=[^=]|[\w.]+\([^)]*\)\s*;?\s*$)",
    re.MULTILINE,
)
TODO_RE = re.compile(r"(?://|#|/\*|\*)[ \t]*(?:TODO|FIXME|HACK|XXX|WIP|LATER)\b", re.IGNORECASE)
STUB_RE = re.compile(
    r"NotImplementedError|not[ _]implemented|TODO\(\)|unimplemented!\("
    r"|throw new UnsupportedOperationException|abstract[ \t]+method",
    re.IGNORECASE,
)
GLOBAL_STATE_RE = {
    "python": re.compile(
        r"^[A-Za-z_]\w*[ \t]*=[ \t]*(?:\[\]|\{\}|set\(\)|dict\(|list\(|defaultdict)", re.MULTILINE
    ),
    "javascript": re.compile(
        r"^(?:export[ \t]+)?(?:let|var)[ \t]+\w+[ \t]*=[ \t]*(?:\[|\{)", re.MULTILINE
    ),
    "go": re.compile(r"^var[ \t]+\w+[ \t]+(?:map\[|\[\]|\*)", re.MULTILINE),
}
GLOBAL_STATE_RE["typescript"] = GLOBAL_STATE_RE["javascript"]

# Infrastructure reached for directly: the DIP signal is how far it spreads.
INFRA_RE = re.compile(
    r"psycopg\d?|sqlalchemy|pymongo|redis\.|boto3|requests\.(?:get|post|put|delete)"
    r"|urllib\.request|http\.client|axios\.|fetch\(|node-fetch|mongoose|knex|pg\.Pool"
    r"|sql\.Open|gorm\.|http\.(?:Get|Post|Client)|net/http|DriverManager|JdbcTemplate"
    r"|HttpClient|RestTemplate|SqlConnection|PDO\(|mysqli_|curl_init|File\.(?:Open|ReadAll)"
    r"|open\([^)]*['\"][wra]|os\.(?:remove|mkdir|rename)|smtplib|sendgrid|stripe\.",
    re.IGNORECASE,
)
CONCERN_RE = {
    "database": re.compile(
        r"psycopg|sqlalchemy|sqlite3|pymongo|redis|gorm|jdbc|mysqli|mongoose"
        r"|knex|SqlConnection|\bsql\b",
        re.IGNORECASE,
    ),
    "http": re.compile(
        r"requests\.|axios|fetch\(|net/http|HttpClient|RestTemplate|urllib|flask"
        r"|fastapi|express|gin-gonic|spring",
        re.IGNORECASE,
    ),
    "filesystem": re.compile(
        r"\bos\.path|pathlib|fs\.readFile|ioutil|File\.Open|fopen", re.IGNORECASE
    ),
    "ui": re.compile(r"react|vue|angular|swing|tkinter|template|render\(|jsx", re.IGNORECASE),
    "crypto": re.compile(r"hashlib|bcrypt|jwt|crypto\.|openssl|argon2", re.IGNORECASE),
    "queue": re.compile(r"kafka|rabbitmq|celery|sqs|pubsub|amqp", re.IGNORECASE),
}
VAGUE_NAMES = {
    "data",
    "info",
    "item",
    "items",
    "obj",
    "object",
    "value",
    "val",
    "temp",
    "tmp",
    "result",
    "res",
    "ret",
    "foo",
    "bar",
    "baz",
    "thing",
    "things",
    "stuff",
    "handler",
    "manager",
    "helper",
    "helpers",
    "util",
    "utils",
    "utility",
    "utilities",
    "process",
    "handle",
    "do",
    "run",
    "execute",
    "perform",
    "misc",
    "common",
    "base",
    "core",
    "main",
    "wrapper",
    "impl",
}
INTERFACE_RE = {
    "python": re.compile(r"class[ \t]+(\w+)[ \t]*\([^)]*(?:ABC|Protocol|abstractmethod)"),
    "java": re.compile(r"(?:^|\s)interface[ \t]+(\w+)"),
    "typescript": re.compile(r"(?:^|\s)interface[ \t]+(\w+)"),
    "go": re.compile(r"^type[ \t]+(\w+)[ \t]+interface", re.MULTILINE),
    "csharp": re.compile(r"(?:^|\s)interface[ \t]+(I\w+)"),
    "php": re.compile(r"(?:^|\s)interface[ \t]+(\w+)"),
    "rust": re.compile(r"(?:^|\s)trait[ \t]+(\w+)"),
    "scala": re.compile(r"(?:^|\s)trait[ \t]+(\w+)"),
}
INTERFACE_RE["kotlin"] = INTERFACE_RE["java"]
IMPLEMENTS_RE = re.compile(r"(?:implements|extends|impl|:)\s+([\w, ]+)")

# Per-language tolerances: Go functions carry explicit error handling, Java
# carries ceremony, Python and Ruby are terse and should stay small.
LANGUAGE_PROFILES = {
    #             max_lines  max_complexity  max_params  max_nesting
    "python": (40, 10, 5, 4),
    "javascript": (40, 10, 4, 4),
    "typescript": (40, 10, 4, 4),
    "go": (60, 12, 5, 4),
    "java": (50, 12, 5, 4),
    "kotlin": (40, 10, 5, 4),
    "csharp": (50, 12, 5, 4),
    "ruby": (25, 8, 4, 3),
    "php": (45, 10, 5, 4),
    "rust": (50, 12, 5, 4),
    "elixir": (20, 6, 4, 3),
    "scala": (35, 10, 4, 4),
    "shell": (40, 10, 5, 3),
    "c": (60, 14, 6, 4),
    "cpp": (60, 14, 6, 4),
}
DEFAULT_PROFILE = (45, 11, 5, 4)


def blend_profile(language_lines):
    """Weight each ecosystem's tolerances by how much of the code it is."""
    total = sum(language_lines.values())
    if not total:
        return {
            "max_lines": DEFAULT_PROFILE[0],
            "max_complexity": DEFAULT_PROFILE[1],
            "max_params": DEFAULT_PROFILE[2],
            "max_nesting": DEFAULT_PROFILE[3],
            "languages": [],
        }
    values = [0.0, 0.0, 0.0, 0.0]
    for lang, lines in language_lines.items():
        profile = LANGUAGE_PROFILES.get(lang, DEFAULT_PROFILE)
        share = lines / total
        values = [v + p * share for v, p in zip(values, profile)]
    return {
        "max_lines": round(values[0]),
        "max_complexity": round(values[1]),
        "max_params": round(values[2]),
        "max_nesting": round(values[3], 1),
        "languages": sorted(language_lines, key=language_lines.get, reverse=True)[:2],
    }


def read_text(path: Path):
    try:
        if path.stat().st_size > MAX_FILE_BYTES:
            return None
        return path.read_text(errors="replace")
    except OSError:
        return None


def walk(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for name in sorted(filenames):
            abs_path = Path(dirpath) / name
            rel = abs_path.relative_to(root)
            if any(p in ARTIFACT_DIRS for p in rel.parts[:-1]):
                continue
            yield abs_path, rel


def is_test_file(rel: Path):
    stem, suffix = rel.stem, rel.suffix
    parts = {p.lower() for p in rel.parts[:-1]}
    if parts & TEST_DIR_NAMES or suffix == ".feature":
        return True
    if suffix == ".py":
        return stem.startswith("test_") or stem.endswith("_test") or stem == "conftest"
    if suffix in JS_EXT:
        return bool(re.search(r"\.(test|spec)$", stem))
    if suffix == ".go":
        return stem.endswith("_test")
    if suffix in {".java", ".kt", ".cs"}:
        return stem.endswith(("Test", "Tests", "Spec"))
    if suffix == ".rb":
        return stem.endswith(("_spec", "_test"))
    if suffix == ".php":
        return stem.endswith("Test")
    return False


def line_of(text: str, offset: int):
    return text.count("\n", 0, offset) + 1


def body_of(text: str, start: int, lang: str):
    """The source of one function, by brace matching or by indentation."""
    if lang in BRACE_LANGS:
        opening = text.find("{", start)
        if opening == -1 or opening - start > 400:
            return text[start : start + 400]
        depth = 0
        for index in range(opening, len(text)):
            char = text[index]
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    return text[start : index + 1]
        return text[start:]
    lines = text[start:].splitlines()
    if not lines:
        return ""
    base = len(lines[0]) - len(lines[0].lstrip())
    body = [lines[0]]
    for line in lines[1:]:
        if line.strip() and (len(line) - len(line.lstrip())) <= base:
            break
        body.append(line)
    return "\n".join(body)


def signature_window(body: str, name: str, span=400):
    """The text just after a function's name, where its parameters live."""
    position = body.find(name)
    if position == -1:
        return body[:span]
    start = position + len(name)
    return body[start : start + span]


def nesting_depth(body: str, lang: str):
    if lang in BRACE_LANGS:
        depth = peak = 0
        for char in body:
            if char == "{":
                depth += 1
                peak = max(peak, depth)
            elif char == "}":
                depth = max(0, depth - 1)
        return max(0, peak - 1)
    lines = [ln for ln in body.splitlines() if ln.strip()]
    if not lines:
        return 0
    base = len(lines[0]) - len(lines[0].lstrip())
    indents = sorted({len(ln) - len(ln.lstrip()) for ln in lines[1:]})
    unit = min((i - base for i in indents if i > base), default=4) or 4
    deepest = max((len(ln) - len(ln.lstrip()) for ln in lines[1:]), default=base)
    return max(0, round((deepest - base) / unit) - 1)


# `self` is not a parameter the caller passes; counting it penalises every
# method against every free function.
IMPLICIT_FIRST_PARAM = {"python"}
IMPLICIT_NAMES = {"self", "cls", "this", "$this"}


def count_params(signature: str, implicit_self=False):
    """Count declared parameters, across line breaks and nested generics."""
    start = signature.find("(")
    if start == -1:
        return 0
    depth = 0
    collected = []
    for char in signature[start:]:
        if char in "([{":
            depth += 1
            if depth == 1:
                continue
        elif char in ")]}":
            depth -= 1
            if depth == 0:
                break
        collected.append(char)
    parts = [
        part.strip()
        for part in re.split(r",(?![^(\[{<]*[)\]}>])", "".join(collected))
        if part.strip()
    ]
    if implicit_self and parts and parts[0].split(":")[0].strip() in IMPLICIT_NAMES:
        parts = parts[1:]
    return len(parts)


# ------------------------------------------------------------- file analysis


def analyse_file(rel: Path, text: str, lang: str, profile):
    """Per-function and per-class measurements for one source file.

    Structure is read from `code` — the source with comments and string
    contents blanked — while the comment-shaped signals (TODOs, commented-out
    code) and the import and infrastructure markers are read from the original,
    where the strings they live in still exist.
    """
    func_re = FUNC_RE.get(lang)
    class_re = CLASS_RE.get(lang)
    code = strip_noise(text, lang)
    lines = [ln for ln in text.splitlines() if ln.strip()]
    info = {
        "file": str(rel),
        "lang": lang,
        "lines": len(lines),
        "code": code,
        "functions": [],
        "classes": [],
        "findings": [],
        "demeter": len(DEMETER_RE.findall(code)),
        "todos": len(TODO_RE.findall(text)),
        "commented_code": len(COMMENTED_CODE_RE.findall(text)),
        "stubs": len(STUB_RE.findall(code)),
        "globals": len(GLOBAL_STATE_RE[lang].findall(code)) if lang in GLOBAL_STATE_RE else 0,
        "infra": len(INFRA_RE.findall(text)),
        "concerns": {name for name, pattern in CONCERN_RE.items() if pattern.search(text)},
        "imports": [],
    }

    import_re = IMPORT_RE.get(lang)
    if import_re:
        for match in import_re.finditer(text):
            for group in match.groups():
                if not group:
                    continue
                for part in group.split(","):
                    target = part.strip().strip("()").split(" as ")[0].strip()
                    if target:
                        info["imports"].append(target)

    if class_re:
        for match in class_re.finditer(code):
            name = match.group(1)
            bases = (
                (match.group(2) or "").strip() if match.lastindex and match.lastindex > 1 else ""
            )
            info["classes"].append(
                {"name": name, "bases": bases, "line": line_of(code, match.start())}
            )

    if func_re:
        for match in func_re.finditer(code):
            groups = [g for g in match.groups() if g is not None]
            name = groups[-1] if groups else "?"
            if name in {"if", "for", "while", "switch", "catch", "return"}:
                continue
            body = body_of(code, match.start(), lang)
            body_lines = [ln for ln in body.splitlines() if ln.strip()]
            function = {
                "name": name,
                "line": line_of(code, match.start()),
                "lines": len(body_lines),
                "complexity": 1 + len(DECISION_RE.findall(body)),
                "nesting": nesting_depth(body, lang),
                "params": count_params(
                    signature_window(body, name), implicit_self=lang in IMPLICIT_FIRST_PARAM
                ),
                "flag_params": len(
                    re.findall(r"=\s*(?:True|False|true|false)\b", body.split("\n", 1)[0])
                ),
                "body": body,
            }
            info["functions"].append(function)
            for label, value, limit, kind in (
                ("lines", function["lines"], profile["max_lines"], "long-function"),
                (
                    "complexity",
                    function["complexity"],
                    profile["max_complexity"],
                    "complex-function",
                ),
                ("nesting", function["nesting"], profile["max_nesting"], "deep-nesting"),
                ("params", function["params"], profile["max_params"], "many-parameters"),
            ):
                if value > limit:
                    info["findings"].append(
                        {
                            "file": str(rel),
                            "line": function["line"],
                            "kind": kind,
                            "message": f"`{name}` has {value} {label} (limit {limit:g})",
                        }
                    )
    return info


NORMALISE_RE = re.compile(r"'[^'\n]*'|\"[^\"\n]*\"|`[^`\n]*`|\b\d+(?:\.\d+)?\b")
COMMENT_LINE_RE = re.compile(r"^[ \t]*(?:#|//|\*|/\*)")


def normalise_line(line: str):
    return re.sub(r"\s+", " ", NORMALISE_RE.sub("@", line)).strip()


STATEMENT_RE = re.compile(r"[-+*/%=<>!]=?|\breturn\b|\bif\b|\bfor\b|\bwhile\b|\w+\s*\(")
DECLARATION_RE = re.compile(r"^\s*(?:import|from|package|use|require|#include|\w+\s*:\s*[\"'@])")


def find_duplicate_blocks(files, window=8, limit=20):
    """Windows of consecutive lines that appear verbatim somewhere else.

    Framework boilerplate — a struct literal of declarations, a block of
    imports — repeats legitimately and would otherwise dominate, so a window
    only counts when most of it is actual statements.
    """
    seen = {}
    duplicated_lines = set()
    findings = []
    reported = set()
    for path, text in files:
        rows = [
            (index + 1, normalise_line(line))
            for index, line in enumerate(text.splitlines())
            if line.strip() and not COMMENT_LINE_RE.match(line)
        ]
        for start in range(len(rows) - window + 1):
            chunk = rows[start : start + window]
            block = "\n".join(line for _, line in chunk)
            if len(block) < window * 14:
                continue
            statements = sum(
                1
                for _, line in chunk
                if STATEMENT_RE.search(line) and not DECLARATION_RE.match(line)
            )
            if statements < window * 0.6:
                continue
            origin = seen.get(block)
            if origin is None:
                seen[block] = (path, chunk[0][0])
                continue
            if origin[0] == path and abs(origin[1] - chunk[0][0]) < window:
                continue
            # Sliding windows overlap, so each duplicated line is counted once:
            # summing window lengths can report more duplicated lines than the
            # file has.
            duplicated_lines.update((path, number) for number, _ in chunk)
            key = (path, chunk[0][0] // window)
            if key not in reported and len(findings) < limit:
                reported.add(key)
                findings.append(
                    {
                        "file": path,
                        "line": chunk[0][0],
                        "kind": "duplicate-block",
                        "message": f"{window} lines repeated from {origin[0]}:{origin[1]}",
                    }
                )
    return len(duplicated_lines), findings


def find_cycles(graph, limit=10):
    """Import cycles between the repo's own modules."""
    colour = {}
    stack = []
    cycles = []

    def visit(node):
        colour[node] = 1
        stack.append(node)
        for neighbour in sorted(graph.get(node, ())):
            if colour.get(neighbour, 0) == 0:
                visit(neighbour)
            elif colour.get(neighbour) == 1 and len(cycles) < limit:
                start = stack.index(neighbour)
                cycles.append(stack[start:] + [neighbour])
        stack.pop()
        colour[node] = 2

    for node in sorted(graph):
        if colour.get(node, 0) == 0:
            visit(node)
    return cycles


# ------------------------------------------------------------------- churn

FIX_LIMIT = 800


def git_churn(root: Path, limit=FIX_LIMIT):
    """How many commits touched each file, keyed the same way as the scan.

    `git log` reports paths from the repository root, so when the scan starts
    in a subdirectory the prefix is stripped — otherwise nothing ever matches
    and the dimension silently scores nothing.
    """

    def run(*args):
        try:
            result = subprocess.run(
                ["git", "-C", str(root), *args],
                capture_output=True,
                text=True,
                timeout=60,
                check=False,
            )
        except (OSError, subprocess.SubprocessError):
            return None
        return result.stdout if result.returncode == 0 else None

    prefix = run("rev-parse", "--show-prefix")
    if prefix is None:
        return {}
    prefix = prefix.strip()
    log = run(
        "log", "-n", str(limit), "--no-merges", "--name-only", "--pretty=format:%x00", "--", "."
    )
    if not log:
        return {}
    counts = Counter()
    for line in log.splitlines():
        path = line.strip()
        if not path or path.startswith("\x00"):
            continue
        if prefix:
            if not path.startswith(prefix):
                continue
            path = path[len(prefix) :]
        counts[path] += 1
    return dict(counts)


def find_hotspots(churn_counts, file_complexity, limit=10):
    """Complexity that sits where the changes land is the expensive kind."""
    scored = [
        (path, churn_counts.get(path, 0), complexity)
        for path, complexity in file_complexity.items()
    ]
    changed = [entry for entry in scored if entry[1] > 1]
    # Enough files to have a meaningful average, and enough churn to rank by.
    # Three files hammered while the rest sit still is the hotspot case, not a
    # reason to give up on it.
    if len(scored) < 5 or len(changed) < 3:
        return None
    changed.sort(key=lambda entry: (-entry[1], entry[0]))
    hot_count = max(3, round(len(changed) * 0.2))
    hot = changed[:hot_count]
    overall = sum(complexity for _, _, complexity in scored) / max(len(scored), 1)
    hot_average = sum(complexity for _, _, complexity in hot) / len(hot)
    findings = []
    for path, commits, complexity in sorted(hot, key=lambda e: -(e[1] * e[2])):
        if complexity <= overall or len(findings) >= limit:
            continue
        findings.append(
            {
                "file": path,
                "line": 1,
                "kind": "hotspot",
                "message": f"changed {commits} times and carries {complexity} complexity "
                f"(codebase average {overall:.0f}) — the expensive kind",
            }
        )
    return {
        "hot_files": len(hot),
        "hot_complexity": round(hot_average, 1),
        "average_complexity": round(overall, 1),
        "findings": findings,
    }


# ----------------------------------------------------------------- collect


def collect(root: Path):
    stats = {
        "root": str(root.resolve()),
        "files": 0,
        "lines": 0,
        "generated_skipped": 0,
        "languages": Counter(),
        "language_lines": Counter(),
        "functions": 0,
        "classes": 0,
        "findings": [],
        "long_functions": 0,
        "complex_functions": 0,
        "deep_functions": 0,
        "wide_functions": 0,
        "flag_params": 0,
        "complexity_total": 0,
        "god_files": 0,
        "wide_classes": 0,
        "mixed_concern_files": 0,
        "type_switches": 0,
        "type_checks": 0,
        "interfaces": 0,
        "fat_interfaces": 0,
        "single_impl_interfaces": 0,
        "stub_overrides": 0,
        "subclasses": 0,
        "infra_files": 0,
        "global_state": 0,
        "duplicate_lines": 0,
        "magic_literals": 0,
        "demeter_chains": 0,
        "cycles": [],
        "fan_out_total": 0,
        "modules": 0,
        "dead_symbols": 0,
        "todos": 0,
        "commented_code": 0,
        "stubs": 0,
        "vague_names": 0,
        "named_things": 0,
        "cohesion_classes": 0,
        "cohesion_score": 0.0,
        "hot_files": 0,
        "hot_complexity": 0.0,
        "average_complexity": 0.0,
        "profile": None,
    }
    sources = []
    for abs_path, rel in walk(root):
        lang = LANG_BY_EXT.get(rel.suffix)
        if lang is None or is_test_file(rel):
            continue
        text = read_text(abs_path)
        if text is None:
            continue
        if is_generated(rel, text):
            stats["generated_skipped"] += 1
            continue
        sources.append((rel, text, lang))
        stats["languages"][lang] += 1
        stats["language_lines"][lang] += sum(1 for line in text.splitlines() if line.strip())

    profile = blend_profile(stats["language_lines"])
    stats["profile"] = profile

    graph = defaultdict(set)
    module_names = {rel.stem for rel, _, _ in sources}
    literals = Counter()
    all_text = []
    infos = []

    for rel, text, lang in sources:
        info = analyse_file(rel, text, lang, profile)
        infos.append(info)
        all_text.append(info["code"])
        stats["files"] += 1
        stats["lines"] += info["lines"]
        stats["functions"] += len(info["functions"])
        stats["classes"] += len(info["classes"])
        stats["findings"].extend(info["findings"])
        stats["demeter_chains"] += info["demeter"]
        stats["todos"] += info["todos"]
        stats["commented_code"] += info["commented_code"]
        stats["stubs"] += info["stubs"]
        stats["global_state"] += info["globals"]
        if info["infra"]:
            stats["infra_files"] += 1
        if len(info["concerns"]) >= 3:
            stats["mixed_concern_files"] += 1
            stats["findings"].append(
                {
                    "file": info["file"],
                    "line": 1,
                    "kind": "mixed-concerns",
                    "message": f"touches {', '.join(sorted(info['concerns']))} in one file",
                }
            )

        for function in info["functions"]:
            stats["complexity_total"] += function["complexity"]
            stats["long_functions"] += function["lines"] > profile["max_lines"]
            stats["complex_functions"] += function["complexity"] > profile["max_complexity"]
            stats["deep_functions"] += function["nesting"] > profile["max_nesting"]
            stats["wide_functions"] += function["params"] > profile["max_params"]
            stats["flag_params"] += function["flag_params"]
            stats["named_things"] += 1
            if function["name"].lower() in VAGUE_NAMES or len(function["name"]) <= 2:
                stats["vague_names"] += 1

        # A file that is most of a subsystem on its own.
        if info["lines"] > 400 or len(info["functions"]) > 20:
            stats["god_files"] += 1
            stats["findings"].append(
                {
                    "file": info["file"],
                    "line": 1,
                    "kind": "god-file",
                    "message": f"{info['lines']} lines, {len(info['functions'])} functions, "
                    f"{len(info['classes'])} classes — more than one reason to change",
                }
            )
        for klass in info["classes"]:
            stats["named_things"] += 1
            if klass["name"].lower() in VAGUE_NAMES or klass["name"].lower().endswith(
                ("manager", "helper", "util", "utils", "processor", "handler", "data")
            ):
                stats["vague_names"] += 1
            if klass["bases"].strip():
                stats["subclasses"] += 1

        # OCP: branching on a type or kind instead of dispatching on it.
        stats["type_switches"] += len(
            re.findall(
                r"(?:if|elif|else if|case|when)[^\n:{]{0,40}\b(?:type|kind|sort|category|status)\b"
                r"[^\n]{0,30}==",
                info["code"],
            )
        )
        stats["type_checks"] += len(
            re.findall(
                r"isinstance\(|instanceof\b|\.GetType\(\)|reflect\.TypeOf|\.class\s*==|is_a\?",
                info["code"],
            )
        )

        interface_re = INTERFACE_RE.get(lang)
        if interface_re:
            for match in interface_re.finditer(info["code"]):
                stats["interfaces"] += 1
                block = body_of(info["code"], match.start(), lang)
                methods = len(FUNC_RE[lang].findall(block)) if lang in FUNC_RE else 0
                if methods > 7:
                    stats["fat_interfaces"] += 1
                    stats["findings"].append(
                        {
                            "file": info["file"],
                            "line": line_of(text, match.start()),
                            "kind": "fat-interface",
                            "message": f"`{match.group(1)}` declares {methods} methods — "
                            "clients depend on more than they use",
                        }
                    )
        if len(info["classes"]) and lang in FUNC_RE:
            methods_per_class = len(info["functions"]) / len(info["classes"])
            if methods_per_class > 15:
                stats["wide_classes"] += 1

        for match in MAGIC_NUMBER_RE.finditer(info["code"]):
            literals[match.group(0)] += 1

        module = rel.stem
        for target in info["imports"]:
            leaf = re.split(r"[./\\:]", target.strip("./"))[-1]
            if leaf and leaf != module and leaf in module_names:
                graph[module].add(leaf)

    stats["modules"] = len(module_names)
    stats["fan_out_total"] = sum(len(v) for v in graph.values())
    stats["cycles"] = find_cycles(graph)
    for cycle in stats["cycles"][:5]:
        stats["findings"].append(
            {
                "file": " -> ".join(cycle),
                "line": 0,
                "kind": "dependency-cycle",
                "message": "modules import each other in a loop — neither can be understood alone",
            }
        )

    duplicate_lines, duplicate_findings = find_duplicate_blocks(
        [(info["file"], info["code"]) for info in infos]
    )
    stats["duplicate_lines"] = duplicate_lines
    stats["findings"].extend(duplicate_findings)

    corpus = "\n".join(all_text)
    stats["magic_literals"] = sum(
        1
        for value, count in literals.items()
        if count >= 4 and value not in {"10", "100", "1000", "24", "60"}
    )

    # YAGNI: private helpers nobody calls, and abstractions with one implementer.
    for info in infos:
        for function in info["functions"]:
            name = function["name"]
            private = name.startswith("_") or (info["lang"] == "go" and name[:1].islower())
            if private and len(name) > 3 and corpus.count(name) <= 1:
                stats["dead_symbols"] += 1
                if len([f for f in stats["findings"] if f["kind"] == "dead-code"]) < 20:
                    stats["findings"].append(
                        {
                            "file": info["file"],
                            "line": function["line"],
                            "kind": "dead-code",
                            "message": f"`{name}` is private and never referenced",
                        }
                    )
        for klass in info["classes"]:
            if not klass["bases"].strip():
                continue
            for base in re.findall(r"\w+", klass["bases"]):
                if base in {"extends", "implements", "object", "Exception", "Enum", "ABC"}:
                    continue
                implementers = len(re.findall(rf"(?:extends|implements|:|\()\s*{base}\b", corpus))
                if implementers == 1:
                    stats["single_impl_interfaces"] += 1
                break
        stats["stub_overrides"] += info["stubs"]

    # Cohesion: how much of a class's own state its methods actually use.
    for info in infos:
        if not info["classes"] or info["lang"] not in {
            "python",
            "ruby",
            "javascript",
            "typescript",
            "php",
        }:
            continue
        fields = set(
            re.findall(r"(?:self|this)\.(\w+)\s*=", "\n".join(f["body"] for f in info["functions"]))
        )
        if not fields or len(info["functions"]) < 3:
            continue
        used = [
            len({m for m in re.findall(r"(?:self|this)\.(\w+)", f["body"]) if m in fields})
            for f in info["functions"]
        ]
        share = sum(1 for count in used if count) / len(used)
        stats["cohesion_classes"] += 1
        stats["cohesion_score"] += share

    hotspots = find_hotspots(
        git_churn(root),
        {info["file"]: sum(f["complexity"] for f in info["functions"]) for info in infos},
    )
    if hotspots:
        stats["hot_files"] = hotspots["hot_files"]
        stats["hot_complexity"] = hotspots["hot_complexity"]
        stats["average_complexity"] = hotspots["average_complexity"]
        stats["findings"].extend(hotspots["findings"])

    stats["findings"].sort(key=lambda f: (f["kind"], f["file"], f["line"]))
    return stats


# -------------------------------------------------------------------- score

DIMENSIONS = [
    ("kiss", "Simplicity (KISS)", 13),
    ("hotspots", "Hotspots (churn x complexity)", 6),
    ("dry", "Duplication (DRY)", 11),
    ("srp", "Single responsibility", 9),
    ("ocp", "Open/closed", 8),
    ("lsp", "Liskov substitution", 5),
    ("isp", "Interface segregation", 6),
    ("dip", "Dependency inversion", 8),
    ("coupling", "Coupling (GRASP)", 9),
    ("cohesion", "Cohesion (GRASP)", 7),
    ("demeter", "Law of Demeter", 5),
    ("yagni", "Speculative generality (YAGNI)", 8),
    ("naming", "Naming & intent", 5),
]
GRADES = [(85, "A"), (70, "B"), (55, "C"), (40, "D"), (0, "F")]


def clamp(value, low=0.0, high=1.0):
    return max(low, min(high, value))


def penalise(pairs):
    """Turn (label, ratio, target, weight) tuples into a score and a detail line."""
    penalties = [
        (label, weight * clamp(ratio / target)) for label, ratio, target, weight in pairs if ratio
    ]
    score = clamp(1 - sum(value for _, value in penalties))
    return score, penalties


def score_kiss(s):
    functions = s["functions"]
    if not functions:
        return None, "no functions found", ""
    profile = s["profile"]
    score, penalties = penalise(
        [
            (
                f"{s['complex_functions']} over complexity {profile['max_complexity']}",
                s["complex_functions"] / functions,
                0.15,
                0.35,
            ),
            (
                f"{s['long_functions']} over {profile['max_lines']} lines",
                s["long_functions"] / functions,
                0.15,
                0.30,
            ),
            (
                f"{s['deep_functions']} nested deeper than {profile['max_nesting']:g}",
                s["deep_functions"] / functions,
                0.10,
                0.20,
            ),
            (
                f"{s['wide_functions']} with more than {profile['max_params']} parameters",
                s["wide_functions"] / functions,
                0.10,
                0.15,
            ),
        ]
    )
    average = s["complexity_total"] / functions
    detail = f"{average:.1f} average complexity over {functions} functions"
    if penalties:
        detail += ", " + ", ".join(label for label, _ in penalties)
    return (
        score,
        detail,
        (
            "split the worst offenders: a function past ~10 branches or ~40 lines "
            "is doing several things and hiding the seams between them"
        ),
    )


def score_hotspots(s):
    """Complexity in the files that change most is the complexity that costs."""
    if not s["hot_files"]:
        return None, "no churn history to rank by", ""
    hot, overall = s["hot_complexity"], s["average_complexity"]
    if overall <= 0:
        return None, "no complexity to weigh", ""
    ratio = hot / overall
    score = clamp(1 - (ratio - 1))
    detail = (
        f"the {s['hot_files']} most-changed files average {hot:g} complexity "
        f"against {overall:g} across the codebase ({ratio:.1f}x)"
    )
    return (
        score,
        detail,
        (
            "refactor where the changes land: complexity in a file nobody touches "
            "is a fact, complexity in one that changes weekly is a bill"
        ),
    )


def score_dry(s):
    if not s["lines"]:
        return None, "no code found", ""
    duplicate_share = s["duplicate_lines"] / s["lines"]
    score, _ = penalise(
        [
            (f"{s['duplicate_lines']} duplicated lines", duplicate_share, 0.05, 0.7),
            (
                f"{s['magic_literals']} repeated magic literals",
                s["magic_literals"] / max(s["files"], 1),
                1.0,
                0.3,
            ),
        ]
    )
    detail = f"{duplicate_share * 100:.1f}% of lines duplicated elsewhere"
    if s["magic_literals"]:
        detail += f", {s['magic_literals']} repeated magic literals"
    return (
        score,
        detail,
        (
            "extract the repeated blocks; duplication is where fixes go to be "
            "applied in three places and forgotten in the fourth"
        ),
    )


def score_srp(s):
    if not s["files"]:
        return None, "no code found", ""
    score, penalties = penalise(
        [
            (f"{s['god_files']} god file(s)", s["god_files"] / s["files"], 0.10, 0.45),
            (
                f"{s['mixed_concern_files']} file(s) mixing 3+ concerns",
                s["mixed_concern_files"] / s["files"],
                0.10,
                0.35,
            ),
            (
                f"{s['wide_classes']} class(es) with 15+ methods",
                s["wide_classes"] / max(s["classes"], 1),
                0.10,
                0.20,
            ),
        ]
    )
    detail = ", ".join(label for label, _ in penalties) or "no god files, no class doing three jobs"
    return (
        score,
        detail,
        (
            "give each module one reason to change: split the files that hold a "
            "subsystem, and move I/O out of the ones that hold rules"
        ),
    )


def score_ocp(s):
    if not s["functions"]:
        return None, "no functions found", ""
    score, penalties = penalise(
        [
            (
                f"{s['type_switches']} branch(es) on a type or kind field",
                s["type_switches"] / s["functions"],
                0.10,
                0.55,
            ),
            (
                f"{s['type_checks']} runtime type check(s)",
                s["type_checks"] / s["functions"],
                0.10,
                0.45,
            ),
        ]
    )
    detail = ", ".join(label for label, _ in penalties) or "no type-branching found"
    return (
        score,
        detail,
        (
            "replace the type switches with polymorphism: every new case should "
            "add a class, not another branch in the same three functions"
        ),
    )


def score_lsp(s):
    if not s["subclasses"]:
        return None, "no inheritance to judge", ""
    score, penalties = penalise(
        [
            (
                f"{s['stub_overrides']} unimplemented override(s)",
                s["stub_overrides"] / s["subclasses"],
                0.15,
                0.6,
            ),
            (
                f"{s['type_checks']} runtime type check(s) around them",
                s["type_checks"] / max(s["subclasses"], 1),
                0.5,
                0.4,
            ),
        ]
    )
    detail = f"{s['subclasses']} subclass(es)"
    if penalties:
        detail += ", " + ", ".join(label for label, _ in penalties)
    return (
        score,
        detail,
        (
            "a subclass that throws NotImplementedError is not substitutable — "
            "split the base type instead of narrowing it"
        ),
    )


def score_isp(s):
    if not s["interfaces"]:
        return None, "no interfaces or protocols declared", ""
    score, penalties = penalise(
        [
            (
                f"{s['fat_interfaces']} interface(s) with 8+ methods",
                s["fat_interfaces"] / s["interfaces"],
                0.20,
                1.0,
            ),
        ]
    )
    detail = f"{s['interfaces']} interface(s)"
    if penalties:
        detail += ", " + ", ".join(label for label, _ in penalties)
    else:
        detail += ", none oversized"
    return (
        score,
        detail,
        (
            "split the wide interfaces: a client forced to implement methods it "
            "never calls is coupled to code it does not use"
        ),
    )


def score_dip(s):
    if not s["files"]:
        return None, "no code found", ""
    spread = s["infra_files"] / s["files"]
    score, _ = penalise(
        [
            (
                f"{s['infra_files']}/{s['files']} files reach infrastructure directly",
                spread,
                0.30,
                0.6,
            ),
            (f"{s['global_state']} mutable global(s)", s["global_state"] / s["files"], 0.20, 0.4),
        ]
    )
    detail = f"{spread * 100:.0f}% of files touch a database, HTTP client or filesystem directly"
    if s["global_state"]:
        detail += f", {s['global_state']} mutable global(s)"
    return (
        score,
        detail,
        (
            "concentrate infrastructure behind a few adapters and inject it, so "
            "the rules can be read and tested without a database"
        ),
    )


def score_coupling(s):
    if s["modules"] < 3:
        return None, "too few modules to judge", ""
    fan_out = s["fan_out_total"] / s["modules"]
    score, _ = penalise(
        [
            (f"{len(s['cycles'])} import cycle(s)", len(s["cycles"]) / s["modules"], 0.05, 0.6),
            (f"{fan_out:.1f} average internal imports per module", fan_out, 8.0, 0.4),
        ]
    )
    detail = f"{fan_out:.1f} internal imports per module"
    if s["cycles"]:
        detail += f", {len(s['cycles'])} cycle(s)"
    return (
        score,
        detail,
        (
            "break the import cycles first — they are the coupling that stops any "
            "module being understood, tested or moved on its own"
        ),
    )


def score_cohesion(s):
    if not s["cohesion_classes"]:
        return None, "no classes with shared state to judge", ""
    share = s["cohesion_score"] / s["cohesion_classes"]
    detail = f"{share * 100:.0f}% of methods use their object's own state"
    return (
        clamp(share / 0.8),
        detail,
        (
            "methods that never touch their object's fields belong "
            "somewhere else — usually next to the data they do use"
        ),
    )


def score_demeter(s):
    if not s["lines"]:
        return None, "no code found", ""
    per_hundred = s["demeter_chains"] / (s["lines"] / 100)
    score = clamp(1 - clamp(per_hundred / 3.0))
    detail = f"{s['demeter_chains']} chains of 3+ dots ({per_hundred:.1f} per 100 lines)"
    return (
        score,
        detail,
        (
            "a.b.c.d ties the caller to the shape of things it does not own — ask "
            "the neighbour for what you need instead of reaching through it"
        ),
    )


def score_yagni(s):
    if not s["functions"]:
        return None, "no functions found", ""
    score, penalties = penalise(
        [
            (
                f"{s['dead_symbols']} unreferenced private symbol(s)",
                s["dead_symbols"] / s["functions"],
                0.05,
                0.35,
            ),
            (
                f"{s['single_impl_interfaces']} abstraction(s) with one implementer",
                s["single_impl_interfaces"] / max(s["classes"], 1),
                0.20,
                0.25,
            ),
            (f"{s['stubs']} unimplemented stub(s)", s["stubs"] / s["functions"], 0.05, 0.20),
            (
                f"{s['commented_code']} block(s) of commented-out code",
                s["commented_code"] / max(s["files"], 1),
                1.0,
                0.10,
            ),
            (f"{s['todos']} TODO/FIXME marker(s)", s["todos"] / max(s["files"], 1), 2.0, 0.10),
        ]
    )
    detail = ", ".join(label for label, _ in penalties) or "no dead code or unused abstraction"
    return (
        score,
        detail,
        (
            "delete what nothing calls and collapse the abstractions with a single "
            "implementer — they cost reading time and buy nothing yet"
        ),
    )


def score_naming(s):
    if not s["named_things"]:
        return None, "nothing named to judge", ""
    share = s["vague_names"] / s["named_things"]
    score = clamp(1 - clamp(share / 0.15))
    detail = (
        f"{s['vague_names']}/{s['named_things']} vague names (manager, helper, data, process, …)"
    )
    if s["flag_params"]:
        score = clamp(score - 0.15 * clamp((s["flag_params"] / s["functions"]) / 0.10))
        detail += f", {s['flag_params']} boolean flag parameter(s)"
    return (
        score,
        detail,
        (
            "name things for what they are: a Manager or a Helper is a class "
            "nobody could describe, and a boolean parameter hides two functions"
        ),
    )


SCORERS = {
    "kiss": score_kiss,
    "hotspots": score_hotspots,
    "dry": score_dry,
    "srp": score_srp,
    "ocp": score_ocp,
    "lsp": score_lsp,
    "isp": score_isp,
    "dip": score_dip,
    "coupling": score_coupling,
    "cohesion": score_cohesion,
    "demeter": score_demeter,
    "yagni": score_yagni,
    "naming": score_naming,
}


def grade_for(score):
    for floor, letter in GRADES:
        if score >= floor:
            return letter
    return "F"


def evaluate(stats):
    results = []
    weighted = total_weight = 0.0
    for key, title, weight in DIMENSIONS:
        score, detail, advice = SCORERS[key](stats)
        entry = {
            "id": key,
            "title": title,
            "weight": weight,
            "score": score,
            "detail": detail,
            "advice": advice,
        }
        if score is None:
            entry["points"] = entry["lost"] = None
        else:
            entry["points"] = round(score * weight, 1)
            entry["lost"] = round((1 - score) * weight, 1)
            weighted += score * weight
            total_weight += weight
        results.append(entry)
    total = round(weighted / total_weight * 100, 1) if total_weight else 0.0
    return {
        "version": VERSION,
        "root": stats["root"],
        "score": total,
        "grade": grade_for(total),
        "scored_weight": total_weight,
        "not_scored": [r["title"] for r in results if r["score"] is None],
        "dimensions": results,
        "findings": stats["findings"],
        "stats": {
            k: (dict(v) if isinstance(v, Counter) else v)
            for k, v in stats.items()
            if k not in {"findings"}
        },
    }


def recommendations(report, top=5):
    ranked = [d for d in report["dimensions"] if d["score"] is not None and d["lost"] >= 0.5]
    ranked.sort(key=lambda d: d["lost"], reverse=True)
    return ranked[:top]


# ------------------------------------------------------------------- render


def bar(score, width=20):
    if score is None:
        return "·" * width
    filled = round(score * width)
    return "█" * filled + "░" * (width - filled)


def location(finding):
    return f"{finding['file']}:{finding['line']}" if finding["line"] else finding["file"]


def render_flags(findings, limit):
    if not findings or limit <= 0:
        return []
    ranked = sorted(findings, key=lambda f: (FLAG_ORDER.get(f["kind"], 9), f["file"], f["line"]))
    shown = ranked[:limit]
    width = max(len(location(f)) for f in shown)
    out = ["", f"Red flags ({len(findings)}):"]
    for finding in shown:
        out.append(f"  {location(finding):<{width}}  {finding['kind']:<18} {finding['message']}")
    if len(findings) > limit:
        out.append(f"  … {len(findings) - limit} more (see --format json)")
    return out


FLAG_ORDER = {
    "hotspot": 0,
    "dependency-cycle": 1,
    "god-file": 2,
    "complex-function": 2,
    "duplicate-block": 3,
    "deep-nesting": 4,
    "mixed-concerns": 5,
    "fat-interface": 6,
    "dead-code": 7,
    "long-function": 8,
    "many-parameters": 9,
}


def render_directories(directories):
    if not directories:
        return []
    width = max(len(d["path"]) for d in directories)
    out = ["", "By directory (worst first):"]
    for entry in directories:
        out.append(
            f"  {entry['grade']}  {entry['score']:5.1f}  {entry['path']:<{width}}  "
            f"{entry['files']:>4} files  → {entry['top_win']}"
        )
    return out


def render_text(report, top=5, max_flags=10):
    stats = report["stats"]
    out = [f"gradebook-code {VERSION} — {report['root']}"]
    langs = ", ".join(f"{k} ({v})" for k, v in list(stats["languages"].items())[:5]) or "none"
    profile = stats.get("profile") or {}
    if profile.get("languages"):
        langs += (
            f"  ·  calibrated for {'/'.join(profile['languages'])}: "
            f"{profile['max_lines']} lines, complexity {profile['max_complexity']}, "
            f"{profile['max_params']} params"
        )
    out.append(f"languages: {langs}")
    counts = (
        f"{stats['files']} files · {stats['lines']:,} lines · {stats['functions']} "
        f"functions · {stats['classes']} classes · {stats['modules']} modules"
    )
    if stats.get("generated_skipped"):
        counts += f" · {stats['generated_skipped']} generated file(s) skipped"
    out.append(counts)
    out.append("")
    for dim in report["dimensions"]:
        points = "  n/a " if dim["score"] is None else f"{dim['points']:5.1f}"
        out.append(
            f"  {dim['title']:<30} {bar(dim['score'])} {points}/{dim['weight']:<3.0f} "
            f"{dim['detail']}"
        )
    out.append("")
    out.append(f"SCORE  {report['score']:.1f}/100   grade {report['grade']}")
    if report["not_scored"]:
        out.append(f"not scored (weights redistributed): {', '.join(report['not_scored'])}")
    wins = recommendations(report, top)
    if wins:
        out.append("")
        out.append("Biggest wins:")
        for dim in wins:
            out.append(f"  +{dim['lost']:<5.1f} {dim['title']} — {dim['advice']}")
    out.extend(render_flags(report.get("findings"), max_flags))
    out.extend(render_directories(report.get("directories")))
    return "\n".join(out)


def render_markdown(report, top=5, max_flags=10):
    stats = report["stats"]
    out = [f"## Code score: **{report['score']:.1f}/100** (grade {report['grade']})", ""]
    out.append(
        f"`{report['root']}` — {stats['files']} files, {stats['lines']:,} lines, "
        f"{stats['functions']} functions, {stats['classes']} classes"
    )
    out.append("")
    out.append("| Principle | Score | Weight | Detail |")
    out.append("|---|---:|---:|---|")
    for dim in report["dimensions"]:
        points = "n/a" if dim["score"] is None else f"{dim['points']:.1f}"
        out.append(f"| {dim['title']} | {points} | {dim['weight']:.0f} | {dim['detail']} |")
    if report["not_scored"]:
        out.append("")
        out.append(f"_Not scored (weights redistributed): {', '.join(report['not_scored'])}._")
    wins = recommendations(report, top)
    if wins:
        out.append("")
        out.append("### Biggest wins")
        for dim in wins:
            out.append(f"- **+{dim['lost']:.1f} {dim['title']}** — {dim['advice']}")
    findings = report.get("findings") or []
    if findings and max_flags > 0:
        out.append("")
        out.append(f"### Red flags ({len(findings)})")
        ranked = sorted(findings, key=lambda f: (FLAG_ORDER.get(f["kind"], 9), f["file"]))
        for finding in ranked[:max_flags]:
            out.append(f"- `{location(finding)}` **{finding['kind']}** — {finding['message']}")
        if len(findings) > max_flags:
            out.append(f"- … {len(findings) - max_flags} more")
    return "\n".join(out)


def score_directories(root: Path):
    results = []
    for child in sorted(p for p in root.iterdir() if p.is_dir()):
        if child.name in SKIP_DIRS or child.name in ARTIFACT_DIRS:
            continue
        stats = collect(child)
        if not stats["files"]:
            continue
        report = evaluate(stats)
        top = recommendations(report, 1)
        results.append(
            {
                "path": child.name,
                "score": report["score"],
                "grade": report["grade"],
                "files": stats["files"],
                "lines": stats["lines"],
                "top_win": top[0]["advice"] if top else "",
            }
        )
    return sorted(results, key=lambda r: r["score"])


# ---------------------------------------------------------------------- cli


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="gradebook-code",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("path", nargs="?", default=".", help="codebase to evaluate")
    parser.add_argument("--format", choices=["text", "json", "markdown"], default="text")
    parser.add_argument(
        "--fail-under", type=float, metavar="N", help="exit 1 when the score is below N (CI gate)"
    )
    parser.add_argument(
        "--baseline", metavar="FILE", help="a previous --format json report to diff against"
    )
    parser.add_argument(
        "--fail-on-drop",
        type=float,
        nargs="?",
        const=0.0,
        metavar="N",
        help="with --baseline, exit 1 when the score drops by more than N",
    )
    parser.add_argument(
        "--by-dir",
        action="store_true",
        help="also score each immediate subdirectory that holds code",
    )
    parser.add_argument("--top", type=int, default=5, metavar="N")
    parser.add_argument("--max-flags", type=int, default=10, metavar="N")
    parser.add_argument("--list-dimensions", action="store_true")
    parser.add_argument("--version", action="version", version=f"gradebook-code {VERSION}")
    args = parser.parse_args(argv)

    if args.list_dimensions:
        for key, title, weight in DIMENSIONS:
            print(f"{key:<10} {weight:>3} pts  {title}")
        print(
            "\nAny dimension without evidence (no interfaces, no inheritance, too few "
            "modules)\nis left unscored and the remaining weights renormalise."
        )
        return 0
    if args.fail_on_drop is not None and not args.baseline:
        print("gradebook-code: --fail-on-drop needs --baseline", file=sys.stderr)
        return 2

    root = Path(args.path)
    if not root.is_dir():
        print(f"gradebook-code: not a directory: {root}", file=sys.stderr)
        return 2

    report = evaluate(collect(root))
    report["recommendations"] = [
        {"dimension": d["id"], "points": d["lost"], "advice": d["advice"]}
        for d in recommendations(report, args.top)
    ]
    if args.by_dir:
        report["directories"] = score_directories(root)
    if args.baseline:
        try:
            with open(args.baseline) as handle:
                baseline = json.load(handle)
            report["baseline"] = {
                "score": baseline["score"],
                "delta": round(report["score"] - baseline["score"], 1),
            }
        except (OSError, ValueError, KeyError) as error:
            print(f"gradebook-code: cannot read baseline {args.baseline}: {error}", file=sys.stderr)
            return 2

    if args.format == "json":
        json.dump(report, sys.stdout, indent=2, default=str)
        print()
    elif args.format == "markdown":
        print(render_markdown(report, args.top, args.max_flags))
    else:
        text = render_text(report, args.top, args.max_flags)
        if "baseline" in report:
            text = text.replace(
                f"grade {report['grade']}",
                f"grade {report['grade']}   {report['baseline']['delta']:+.1f} vs baseline "
                f"({report['baseline']['score']:.1f})",
                1,
            )
        print(text)

    failed = False
    if args.fail_under is not None and report["score"] < args.fail_under:
        print(
            f"gradebook-code: {report['score']:.1f} is below --fail-under {args.fail_under}",
            file=sys.stderr,
        )
        failed = True
    if args.fail_on_drop is not None:
        drop = -report["baseline"]["delta"]
        if drop > args.fail_on_drop:
            print(
                f"gradebook-code: dropped {drop:.1f} points against the baseline", file=sys.stderr
            )
            failed = True
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
