local config = require('gradebook.config')

describe('config', function()
  it('runs both tools on save by default', function()
    local opts = config.resolve({})
    assert.are.same({ 'code', 'tests' }, opts.tools)
    assert.equals('on_save', opts.run)
    assert.equals(400, opts.debounce_ms)
    assert.is_true(opts.enabled)
    assert.is_true(opts.scan_project_on_startup)
    assert.is_true(opts.diagnostics.enabled)
  end)

  it('takes a cmd list, so a checkout needs no install', function()
    local opts = config.resolve({ cmd = { code = { 'python3', '/src/gradebook_code.py' } } })
    assert.are.same({ 'python3', '/src/gradebook_code.py' }, opts.cmd.code)
    -- ... and leaves the other tool alone.
    assert.are.same({ 'gradebook-tests' }, opts.cmd.tests)
  end)

  it('maps every severity bucket onto a diagnostic level', function()
    local severity = config.resolve({}).diagnostics.severity
    assert.equals(vim.diagnostic.severity.ERROR, severity.high)
    assert.equals(vim.diagnostic.severity.WARN, severity.medium)
    assert.equals(vim.diagnostic.severity.HINT, severity.low)
  end)

  it('replaces a list outright rather than merging into it', function()
    assert.are.same({ 'code' }, config.resolve({ tools = { 'code' } }).tools)
  end)

  it('does not leak one resolve into the next', function()
    config.resolve({ tools = { 'code' }, run = 'manual' })
    local opts = config.resolve({})
    assert.are.same({ 'code', 'tests' }, opts.tools)
    assert.equals('on_save', opts.run)
  end)

  describe('validation', function()
    it('rejects an unknown run mode', function()
      assert.has_error(function()
        config.resolve({ run = 'sometimes' })
      end)
    end)

    it('rejects an unknown tool', function()
      assert.has_error(function()
        config.resolve({ tools = { 'style' } })
      end)
    end)

    it('rejects a cmd that is a bare string', function()
      assert.has_error(function()
        config.resolve({ cmd = { code = 'gradebook-code' } })
      end)
    end)

    it('rejects a debounce too short to be a debounce', function()
      assert.has_error(function()
        config.resolve({ debounce_ms = 5 })
      end)
    end)

    it('accepts false for a severity, meaning "do not report these"', function()
      local opts = config.resolve({ diagnostics = { severity = { low = false } } })
      assert.is_false(opts.diagnostics.severity.low)
    end)
  end)
end)
